<a href="https://colab.research.google.com/github/kiki-glitch/2D-House/blob/main/ANN%20Foward%2CBack%20Prpagation%20%26%20MSE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [162]:
import pandas as pd #dataset library
import numpy as np #linear algebra library

In [163]:
from numpy import array
from sklearn.preprocessing import Normalizer 
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform,normal

Hyperparemeters

In [164]:
batch_size=2

In [165]:
data_dict={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70], 'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}
 

In [166]:
data=pd.DataFrame(data_dict)

In [167]:
data

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [168]:
x=data.drop('Target',axis=1)
y=data['Target']

In [169]:
x_trans=Normalizer(norm='max').fit_transform(x)


In [170]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [171]:
y=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [172]:
y

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

In [173]:
x_trans

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

ANN Model From Scratch

In [174]:
"""weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])"""

'weight_1=array([[.2,.1],[.3,.1],[.2,.1]])\nweight_2=array([[.5],[.1]])'

In [175]:
weight_1=uniform(-1,1,(3,2)) #shape of 3 by 2
weight_2=uniform(-1,1,(2,1))

In [176]:
x=x_trans

In [177]:
x[0:batch_size]

array([[0.6, 0.8, 1. ],
       [0.8, 1. , 0.4]])

In [178]:
output_1=x[0:batch_size]@weight_1 #WX i.e. calculating weight matrix by first input of 1st row

In [179]:
output_1

array([[ 0.51277165, -0.16243544],
       [ 0.21152886,  0.2235474 ]])

Performing neurone activation by using Sigmoid function 

In [180]:
act_output_1=sigmoid(output_1).numpy()
act_output_1

array([[0.62545599, 0.4594802 ],
       [0.55268591, 0.55565527]])

In [181]:
final_out=act_output_1@weight_2
final_out

array([[0.22810015],
       [0.29860725]])

In [182]:
y_true=y[0][0:batch_size]
y_true

array([0.28571429, 0.21428571])

In [183]:
y_pred=final_out.T[0]
y_pred

array([0.22810015, 0.29860725])

Computing Mean Squared Error

In [184]:
mse(y_true,y_pred).numpy()

0.005214755365286182